import streamlit as st
st.title("streamlit demo")
st.header("this is HEADER")
st.subheader("this is SUBHEADER")
st.markdown("____")
st.success("this is green")
st.error("this is red")
st.info("this is blue")
st.warning("this is yellow")
st.markdown("___")