print("hello word")
print('hello word')
print("python","java","web")
print("welcom to")
print("benglur")
print("welcom to ",end='')
print("bengaluru")
print("welcom to ",end='/')
print("bengaluru")
print("web","java","python",sep='/')
print("python","java",end=' ',sep='and')
print("are the programing langauge")
