name=input('enter the student name')
id=int(input('enter the student id'))
branch=input('enter the student branch')
email=input('enter the email')
test1=int(input('enter the marks'))
test2=int(input('enter the marks'))
test3=int(input('enter the marks'))
avg=(test1+test2+test3)/3
print("name of student is",name)
print("id of stuent is",id)
print("branch of student is",branch)
print("email of student is",email)
print('avg of test1  test2 test3 is',avg)
print('name \t id \t branch \t email \t test1 \t test2 \t test3 \t avg ')
print('------------------------------------------------------------------')
print(name,"\t",id,"\t",branch,"\t",email,"\t",test1,"\t",test2,"\t",test3,"\t",avg)